#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := z80
EXCLUDE_COMPONENTS := libsodium coap openssl nghttp expat esp_http_client esp-tls aws_iot bt jsmn json ulp

include $(IDF_PATH)/make/project.mk

