#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := imsaisim_esp32
EXCLUDE_COMPONENTS := libsodium coap openssl nghttp freemodbus unity expat mqtt tcp_transport protocomm esp_https_ota esp_https_server esp_http_server esp_http_client esp-tls aws_iot bt jsmn json ulp

include $(IDF_PATH)/make/project.mk
